# Generated by Django 4.1.4 on 2023-05-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='video_question',
            field=models.FileField(null=True, upload_to='Questions/', verbose_name=''),
        ),
    ]
