# Generated by Django 4.1.4 on 2023-05-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
