# Generated by Django 4.1.4 on 2023-05-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='team/')),
                ('designation', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('fblink', models.URLField()),
                ('twitterlink', models.URLField()),
                ('instalink', models.URLField()),
                ('linkedinlink', models.URLField()),
            ],
        ),
    ]
