# Generated by Django 4.1.4 on 2023-05-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='testimonial/')),
                ('designation', models.CharField(max_length=200)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
