# Generated by Django 4.1.4 on 2023-05-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('AL', 'Albania'), ('BZ', 'Belize'), ('IN', 'India'), ('US', 'United States'), ('GB', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('DE', 'Germany'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('RU', 'Russia'), ('CN', 'China'), ('JP', 'Japan'), ('BR', 'Brazil'), ('MX', 'Mexico'), ('AR', 'Argentina'), ('PK', 'Pakistan'), ('EG', 'Egypt'), ('NZ', 'New Zealand'), ('ZA', 'South Africa'), ('BD', 'Bangladesh')], max_length=50),
        ),
    ]
