# Generated by Django 4.1.4 on 2023-05-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='core/UserAssets/img/profile-img.jpg', upload_to='profile_pics'),
        ),
    ]
