# Generated by Django 4.1.4 on 2023-05-16 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='question',
        ),
    ]
