# Generated by Django 4.1.4 on 2023-05-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_remove_analysis_emotion_intelligence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='sentiment_score',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
