# Generated by Django 4.1.4 on 2023-05-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_analysis_sentiment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='sentiment_score',
            field=models.TextField(blank=True, null=True),
        ),
    ]
